### ISSUE TITLE
Align secondary/work profile indicator next to app label

### ISSUE THREAD

**Issue by sheltpat** [OlauncherCF/OlauncherCF#114]
Hello,
I'd like to request a feature or possible default behavior of the dot indicator for apps installed within a work profile (like Shelter uses).

**Current behavior:**
Dot indicator aligns with the very left side of the screen.
If app drawer is centered, the dot remains left and one might need to look closer to click the right app.

**Request:**
An alignment option or having it align next to the app label by default.
Leaving the app label independently centered might be aesthetically desirable.

Having the same app installed in both profiles seems to always display the secondary below the primary one, but this feature might save time double checking which app to launch.

(Also, this dot is always displayed in white, regardless of theme. It is unfortunately invisible on white background, which might be an issue with the non-CF version.)

Many thanks in advance.

**Comment by jooooscha** [comment]
I actuall did not know sheltered apps are marked. This can definitely be improved. Thanka for the issue
