### ISSUE TITLE
Aliases for search or fuzzy find

### ISSUE THREAD

**Issue by guillaumeboehm** [OlauncherCF/OlauncherCF#141]
**Is your feature request related to a problem? Please describe.** 

- I often find that it would be much better to find some apps using shorter names, for example I find myself typing `yt` to search for `youtube` quite often, which obviously doesn't show up.

**Describe the solution you'd like** 

-  Having an opt-in option to search using fuzzy find, or the ability to set custom aliases to apps (only for search results not as a rename) but this solution would probably clutter the UI quite a bit.

**Comment by jooooscha** [comment]
This is an interesting feature. As a first thought, this could be tricky to implement in a stable way.
Fuzzy searching could lead to too many matches. This could cause the "only one app left" case to never be triggered.
Having aliases would require a new screen to manage them. This could be done but would take some time to implement.

For an immediate solution, for any app I use often I know one combination of two to max. three letters that are unique. For example if 'you' would have more than one match, you could try typing 'utu' or 'ube' which are less likely to result in more than one match.

Anyway, I will think about it

**Comment by guillaumeboehm** [comment]
You are right, I don't even know if the aliases solution would be very useful either actually... In my example I have `mightytext` opening when I type `yt` so even with aliases I would not end up with the "only one app left" case as you call it. And having some specific cases for exact match of aliases would be probably pretty jank.

As for the fuzzy search, I very often find it more convenient than regular search anyway, so I might work on it a little bit myself and see how it feels, dipping my toes into kotlin in the process. If adding you are ok with adding the option obviously.

**Comment by jooooscha** [comment]
Sure, go ahead. As I said i have my concerns that this will improve the user experience, but if it works reasonably well, I don't see why we should not add an option for it

**Comment by D-ominik** [comment]
Good idea and useful in another situation: with rarely used apps I sometimes forget their name and then have to read through the whole list.

Your fork already offers the possibility to rename apps even in the app list. This is great. Also to distinguish identically named apps (fortunately there are no icons, but they would help in this case). For the apps I can't remember, I add their purpose in the name and can easily find them (e.g. I add "photo" to the name of an awkwardly named image editing tool).

Perhaps a simple solution to this feature request would be to manually add a special character when renaming the app name and then the new words/abbreviations. In the app list, only the content up to this special character is displayed, but the search uses the complete string and thus also responds to the added expressions.

**Comment by guillaumeboehm** [comment]
@D-ominik I also had this issue a couple times. Although I feel like this could be a separate issue for another feature? I went away from the aliases idea and rather testing fuzzy search right now.

**Comment by jooooscha** [comment]
I think we can keep this thread combined for now. Lets first find out which approach we like best

**Comment by eclairevoyant** [comment]
Just to add to this - rather than just an on/off, would it be considered to have multiple search modes? E.g.
- "contains" (the current search method)
- "word starts with" (e.g. if an app is called "Photographer's companion", I can search using "ph" or using "co" but not something in the middle like "mp")
- "fuzzy" as asked above by others

**Comment by jooooscha** [comment]
Sure, go ahead :)

**Comment by jooooscha** [comment]
Any updates on this?

**Comment by eclairevoyant** [comment]
Same, I can't commit to a timeline atm.
