### ISSUE TITLE
Fix 12H/24H format

### ISSUE THREAD

**Issue by alekksander** [OlauncherCF/OlauncherCF#144]
Customizable date and clock format would be top – for instance to display date as 12.08.2022 instead of shortened week day plus month. Same goes for clock – for now it displays 03:57 – so 12h format but without am/pm, while in europe we use 24h. thanks!

ps. this launcher is really something and it's even better than original project :)

**Comment by jooooscha** [comment]
Please do not spam multiple problems into one issue. 

The 12/24 hour problem has been discussed in #32.

Having an option to specify the time format is a cool idea. But implementation could take a while. So no promises there.

The font size issue is a bug and I will fix it.

**Comment by alekksander** [comment]
sorry… originally it was spitted into two issues but i thought it's better to merge since they are related. thanks for taking interest in such short notice. hoping to see it sooner or later if it works with You :)

**Comment by jooooscha** [comment]
Related issues can be references with a '#' and the number of the issue. Putting them in one issue makes it hard to keep an overview

**Comment by sebastianha** [comment]
I second the request to be able to adjust the font size for the clock / date.

**Comment by jooooscha** [comment]
Solved the font size "bug" in v1.3.2

The rest will be implemented later

**Comment by sebastianha** [comment]
Perhaps another thing which might be handy is to be able to define a top margin for the clock. Now it is very close to the header bar, it would look nicer when it is a little bit lower:

![Screenshot_20221113-105504](https://user-images.githubusercontent.com/420807/201516090-d182abe0-b201-4601-965d-3fe7b6ecdae9.png)

**Comment by jooooscha** [comment]
Please open separate issues for separate problems

**Comment by jooooscha** [comment]
I clead up the issue. Independent font-size is now in #215

**Comment by jooooscha** [comment]
Did not get any new complaints. Assuming this is not an issue anymore
