### ISSUE TITLE
App drawer disappears when I rotate my phone

### ISSUE THREAD

**Issue by CrimsonBloodfang** [OlauncherCF/OlauncherCF#151]
#### Short description 
When I rotate my phone while on the app drawer, the apps listed on the app drawer disappears.

#### Steps to reproduce 
1. Scroll up to view the app drawer
2. Rotate the phone
3. List of apps on the app drawer disappears

#### Environment information 
- Olauncher CF Version: 1.1.0
- Install Source: F-Droid
- Device: Huawei P8 Lite 2017
- Android: 8.0.0, EMUI 8.0.0
- Other: Debloated phone

#### Additional elements

https://user-images.githubusercontent.com/68450471/183234974-80c281ca-7f56-4c30-8b6d-70c24c44027e.mp4

**Comment by jooooscha** [comment]
Again seems to be related to EMUI, on my tablet it just sends me back to the home screen. Like with #152 will be hard to debug for me

**Comment by jooooscha** [comment]
could you write a little note why you closed this?
