### ISSUE TITLE
Uninstall button on tap and hold an app

### ISSUE THREAD

**Issue by nulledone** [OlauncherCF/OlauncherCF#156]
Having an option to uninstall next to info/hide, would be really useful feature.

**Comment by jooooscha** [comment]
Given that the space there is already pretty limited and apps can be uninstalled with only one tap more on the info button, I am not sure this will improve the user experience.
In addition, I assume most people not use that button too often.

What do you think?

**Comment by AntonDzutstsati** [comment]
> What do you think?

Maybe you replace words "Hide", "Rename" with icons? There will be more place after it.

**Comment by eyome** [comment]
It may be quiet surprising for a launcher without icon, but let me suggest these icons for example:
https://materialdesignicons.com/icon/eye-off
https://materialdesignicons.com/icon/rename-box
https://materialdesignicons.com/icon/undo

**Comment by AntonDzutstsati** [comment]
These icons look really good. Would be cool if they'll be added in next update.

**Comment by jooooscha** [comment]
Even with icons the space is limited. I am not sure saving that one click is worth it.

Using icons instead of text is a good idea, though. I will try it out and see how it looks

**Comment by nulledone** [comment]
It really is useful in some use cases. using icons will give the enough space. At least an option to enable it would be really good since not everyone may want or need it, same option should be for all (hide, rename). I use high dpi and even in current state there's a long space :).

If anything above is not in scope of your development, maybe as a last effort, hold info button to prompt uninstall.
