### ISSUE TITLE
Please add support for Progressive Web Apps

### ISSUE THREAD

**Issue by D-ominik** [OlauncherCF/OlauncherCF#157]
There are website that support a kind of  standalone mode (https://en.wikipedia.org/wiki/Progressive_web_application). On mobile devices one can add these websites to the home screen* and when started they appear and act like regular apps, without the browser UI. As an example: https://www.bmw.com/

*) In most mobile browsers there's an entry "Add to homescreen" in the contextual menu, but it may be hidden if the launcher does not support this.

Unfortunately, Olauncher does not offer support for PWAs. I am not an Android developer, but I think that this can't be a big deal, because pretty much every launcher offers this feature...

For more information here's a link to the same request in the original repo: https://github.com/tanujnotes/Olauncher/issues/20

**Comment by jooooscha** [comment]
I will look into this as soon as I have time (which could take a while). But I like the idea

**Comment by jooooscha** [comment]
I have started looking into this, but documentation seems to be rare. From what I can tell, this is more complicated than one might think. Therefore, I cannot guarantee that I will succeed in adding this feature.

If anyone has a good source/documentation for this, I would highly appreciate any hint or link

**Comment by D-ominik** [comment]
Strange, didn't expect this to be difficult because a lot (e.g. Apex launcher, Nova launcher, any stock launcher) launcher support it.

**Comment by jooooscha** [comment]
I strongly suspect both Apex Launcher and Nova Launcher are developed by teams of paid developers. At least both launcher have paid versions. Not that money would be the issue, but time is, and both are equivalent in some regards. Therefore, this is an unfair comparison.
Same goes for stock launchers from let's say Samsung.

As for launchers from lineageOS and similar. They are probably based on some AOSP launcher that already had this feature or at least exist long enough to have figured out how to implement the feature. OlauncherCF on the other hand is based on OlauncherAF, which has been developed by tanujnotes (1 person afaikt) and is now continued by me (1 person; I am quite sure).
Therefore, again, this is not a fair comparison.

I am sure I will find the time to research this, eventually. But for now, please be patient, and if you want to help, you can search for good documentation of this feature.

**Comment by D-ominik** [comment]
Oh, that was in no way against you or your work!

I just spent over an hour myself looking for information on how to add support. I didn't find any hint and was very surprised about it, because the feature is present in many launchers. I suppose it can't really be something hard to add, so it's more surprising that one can't find any information.

**Comment by The-Repo-Club** [comment]
[ShortcutInfo](https://developer.android.com/reference/android/content/pm/ShortcutManager#requestPinShortcut(android.content.pm.ShortcutInfo,%20android.content.IntentSender)) Hope this helps

**Comment by jooooscha** [comment]
Thanks for the link, but that alone won't help me. The problem is that I cannot find any documentation on how to implement those, and I don't have the time for trial-and-error, currently.

**Comment by filipesmedeiros** [comment]
How much would this cost you think, in sponsorship, to make this move forward? :) @jooooscha

**Comment by filipesmedeiros** [comment]
We can track this to collaborate, maybe? https://github.com/tanujnotes/Olauncher/issues/20#issuecomment-1853738030

**Comment by jooooscha** [comment]
Actually, the main problem is not money. It's time and lack of knowledge. As I said before, I don't have any documentation or easy reference implementation. Therefore, I am not able to implement this.

**Comment by filipesmedeiros** [comment]
That is sad to hear but totally valid. If the original issue (https://github.com/tanujnotes/Olauncher/issues/20) gets implemented successfully, do you think you'd be able to port it? :)

Again, if you prefer not to do it, totally fine; this is your project and thank you again for making it free and libre :)

**Comment by jooooscha** [comment]
I will need to take a look at what he is doing before I can make any promises.
