### ISSUE TITLE
Multiple app lists for home screen

### ISSUE THREAD

**Issue by D-ominik** [OlauncherCF/OlauncherCF#158]
There is the home screen app list to which you can add your favorite apps. This is fine the way it is. It would be great to have the option to create multiple "home screen app lists". In the settings, you should then be able to choose which of the app list is the active one (the one shown on the home screen).

The key feature would be a method to programmatically select the active app list. In other words, one could use some kind of API, like "Android Intents" or something else, to control which of the home screen app lists is shown. This way, one could then use any automation app (like Tasker) to control the selection of apps on the home screen.

For example, you could display a different app list at home than at the office. In the car, a different list appears, containing navigation apps, for example.

**Comment by jooooscha** [comment]
I like the Idea. It could be implemented as some kind of profiles

Todos for this just of the top of my head:

- [ ] Interface to create profiles
- [ ] Interface to rename profiles
- [ ] Interface to change between profiles
- [ ] Android Intents to change profiles from tasker

**Comment by jooooscha** [comment]
I now think this does not add enough value to counter the added complexity
