### ISSUE TITLE
Launcher reverts to System language despite setting a different language

### ISSUE THREAD

**Issue by eclairevoyant** [OlauncherCF/OlauncherCF#179]
#### Short description
After some time of using apps and going back to the launcher, the launcher reverts to the System language.
However, the language setting still shows the language I selected.

#### Steps to reproduce
I am unsure of the steps to reproduce.

#### Environment information
- Olauncher CF Version: 1.2.4
- Install Source: F-Droid
- Device: `sofia`
- Android: Stock ROM, Android 11
- EMUI?: Don't know what this is, so probably not.
- Other: 

#### Additional elements
Screenshot of the settings page. In this case, my system's language is English and I selected Chinese as the launcher language.
<img src="https://user-images.githubusercontent.com/848000/189474408-f919f305-bfd5-40e6-bf6b-2d9a7f34ed95.png" width="200" />

**Comment by jooooscha** [comment]
It's going to be hard to debug, if I don't have steps to reproduce. Unless there is a persistent way of debugging, I am afraid there is not much I can do

**Comment by eclairevoyant** [comment]
Is there a debug build that I could use and then try to check logs when it does happen?

**Comment by jooooscha** [comment]
If you know how, the best way would be to clone this repo and add some logging for yourself.
Otherwise, you'd have to wait until I have the time to debug this on my device

**Comment by eclairevoyant** [comment]
I haven't used the launcher in a while, and I no longer have the device that had this issue. Closing as no longer reproducible
