### ISSUE TITLE
More responsiveness when opening the apps menu

### ISSUE THREAD

**Issue by Terkyz** [OlauncherCF/OlauncherCF#182]
**Is your feature request related to a problem? Please describe.** 
No. But the response time can honestly improve, at least on my device (a10) it takes a considerably noticeable time opening the apps menu or "global menu"-

**Describe the solution you'd like** 
More accountability or ability to set the launcher reaction time manually 

**Describe alternatives you've considered** 
Manually adjust it in the settings

**Additional context** 
Manually adjust it in the settings

**Comment by jooooscha** [comment]
I am not sure what you problem is.
Do you mean the time the app list needs to open?
Which time do you want to be adjustable in settings?

Please elaborate in more context and detail what your problem is and how we can help you.

**Comment by Terkyz** [comment]
> I am not sure what you problem is. Do you mean the time the app list needs to open? Which time do you want to be adjustable in settings?
> 
> Please elaborate in more context and detail what your problem is and how we can help you.

Sorry for the late reply and poor explanation.

Within Olauncher, when I slide my finger down to open the list of applications, Olauncher takes about 1 second to open the menu, is it possible to improve that response time?

And adjustable I mean that there is an option in the Olauncher menu that gives me the ability to choose the response time of said menu, between instant or slow, for example

**Comment by jooooscha** [comment]
I wouldn't know why you would choose a response time other than instant.
To be clear, it is intented to be instant; if it is not, that has probably a bug, or your phone is too slow.

The current implementation can certainly be improved, but I don't think I will have the time (or maybe knowledge) to do this currently.

Do you have the same issues with the original version?

Could you also give more information about your specific setup, such as your phone model and OS version.

**Comment by Terkyz** [comment]
> I wouldn't know why you would choose a response time other than instant. To be clear, it is intented to be instant; if it is not, that has probably a bug, or your phone is too slow.
> 
> The current implementation can certainly be improved, but I don't think I will have the time (or maybe knowledge) to do this currently.
> 
> Do you have the same issues with the original version?
> 
> Could you also give more information about your specific setup, such as your phone model and OS version.

Yes, I have the same problem with the original version. 

My device is Samsung a10 with Android 11

**Comment by jooooscha** [comment]
I will mark this as an performance improvement.
But this could take a while to "fix"

**Comment by ANDREW007CZ** [comment]
It's pretty instant on my Xperia 5 III, any noticeable lag whatsoever.

**Comment by miwafoxl** [comment]
I'm also having this problem. Whenever I slide up to show the apps, it shows "No apps found" for about 1 second or 2 and then show the apps lists. I'm using Redmi Note 9, installed Olauncher directly from F-droid.

I found something interesting however, this only appears to happen when I close all the apps open using the android square button, and then clicking the X to close all apps open. Perhaps by doing this I'm closing Olauncher and then it have to load the app list again and again?

I'll upload a video here showing this bug in action.

**Comment by miwafoxl** [comment]
[Download Video Preview (Google Drive)](https://drive.google.com/file/d/1vbgVnx5bo2v0zJ1RVkH7V62U_ejkhvg9/view?usp=drivesdk)  
1st try, before I opened the calculator: normal, as good as it can be;
2nd try, after I closed the calculator: shows "No apps found" then loads the app list. 
(I turned on "Show taps" in the recording so you can see clearly how much it takes to open and close the menu after I performed the gesture)

For me, it appears to be only in that situation. Could be something about battery saving. Still, even when the bug doesn't occur (in the same video) it also appear to lag about half a second. I think its probably looking for a finger gesture of sliding up and not actual registering the amount that I have swiped and applying in on-the-fly.

In Nova7 launcher for example, it also requires you to slide up in order to see all the apps, but I think it doesn't look for this gesture the same way because it's instantaneous and I can actually pause the animation half-way if I not swipe up completely.

**Comment by jooooscha** [comment]
The video helps a lot to under stand your issue.
On which version of the app did you make the video?

**Comment by miwafoxl** [comment]
> The video helps a lot to under stand your issue. On which version of the app did you make the video?

I'm in v1.2.8, the latest version available in F-droid. I saw in the repo here that there is already v1.2.10 which I probably should be using.

**Comment by jooooscha** [comment]
v1.2.10 is not yet available in f-droid. I am not sure why it takes so long this time

**Comment by jooooscha** [comment]
Does this issue still persist for you in v1.2.10?

**Comment by Terkyz** [comment]
> Does this issue still persist for you in v1.2.10?

Not really, honestly it's practically immediate, thanks for fixing it!
