### ISSUE TITLE
Blank main view displaying after search

### ISSUE THREAD

**Issue by Voralberg** [OlauncherCF/OlauncherCF#200]
#### Short description 
Rarely I noticed that for certain applications opened with a search, instead of the application launching directly, the main view of the launcher was shown briefly and then the application was launched. Recently tough I have installed, to make up for the lack of !bang search, [Just Search](https://github.com/veniosg/JustSearch): an _Assist replacement_ that shows a search bar on a layer for quick searches. Opening this search bar when scrolling in the full menu of Olauncher shows a blank main menu (i.e. All the app name are replaced with the default "_App_" placeholder) on the background.

I guess the problem is similar to the original [Olauncher](https://github.com/tanujnotes/Olauncher/issues/197) one.

#### Environment information
- Olauncher CF Version: 1.2.10
- Install Source: F-Droid
- Android: 11 LineageOS

**Comment by jooooscha** [comment]
Thanks for reporting. I am pretty sure where this comes from. I will improve this behavior
