### ISSUE TITLE
Live backgrounds dont get centered

### ISSUE THREAD

**Issue by TubaApollo** [OlauncherCF/OlauncherCF#201]
- [x] I have searched existing issues for this feature.

**Is your feature request related to a problem? Please describe.** 

- Live wallpapers get left alligned instead of centered (e.g. Muzei) -> There is an q&a on muzei github about it which says that this is a launcher issue. 

**Describe the solution you'd like** 

Center backgrounds by default or let the user choose how he wants to have it alligned 

**Describe alternatives you've considered** 

I dont think there is a real alternative of doing that?

**Additional context** 

reproduce (for better context):
Download Muzei
Set it as background and use any landscape image
You can clearly see that it is left alligned

**Comment by jooooscha** [comment]
Mh, I am not sure which part of the launcher is responsible for this. But I will look into it.
Thanks for reporting

**Comment by TubaApollo** [comment]
Thank you for looking into it!
Maybe this post will give you some kind of hint: https://github.com/muzei/muzei/discussions/711

**Comment by TubaApollo** [comment]
Was a configuration problem, works fine for me now.

**Comment by jooooscha** [comment]
Would you mind giving more details in case others run into this problem too?

**Comment by TubaApollo** [comment]
I first thought it was because i disable "Auto crop" inside the background extension, but i recognized that this did not fix it. Instead  i switched the launcher to kiss enabled "Center background" switched back to Olauncher and it was centered again. Only problem is that with every restart the same problem occurs again, so i wouldnt say its a fix..
