### ISSUE TITLE
Don't limit font size to 30

### ISSUE THREAD

**Issue by sebastianha** [OlauncherCF/OlauncherCF#206]
- [x] I have searched existing issues for this feature.

**Is your feature request related to a problem? Please describe.** 

Currently the maximum font size is 30. On my Pixel 7 this could be still larger.

**Describe the solution you'd like** 

Don't limit the font size, let the user decide

**Comment by jooooscha** [comment]
The limits were there, because increasing the font size by too much could render the settings unusable, and there would be no going back.
Therefore, I am now updating the font size immediately on every increase, and the user can see when the font is growing too large.

**Comment by sebastianha** [comment]
mmh, I don't this this was a practical idea. This is how my start screen looks at font size 35

![Screenshot_20221114-210603](https://user-images.githubusercontent.com/420807/201755677-8bd6e528-f866-44ed-a566-18aaa01a55dc.png)

And this are the settings:

![Screenshot_20221114-210633](https://user-images.githubusercontent.com/420807/201755721-15063c3e-1cdd-415a-9d1f-46c7a4e944f5.png)

**Comment by jooooscha** [comment]
Yes noticed that. I did something wrong, which causes the settings to be much bigger than the rest. will fix it in next release
