### ISSUE TITLE
Shorten app list animation or disable it

### ISSUE THREAD

**Issue by sebastianha** [OlauncherCF/OlauncherCF#208]
- [x] I have searched existing issues for this feature.

**Is your feature request related to a problem? Please describe.** 

When opening the full app list there is an animation where the apps fade in from top to bottom. This animation is rather slow and for me the list feels slow. It is usable during the animation but it could feel more "snappy"/better with a very short or no animation.

**Describe the solution you'd like** 

Make the animation shorter or offer a setting to disable it.

**Comment by jooooscha** [comment]
I am not sure what you mean. On my phone the animation is barely noticable.

Would you mind posting a screencast of how it looks on your device?

**Comment by sebastianha** [comment]
It is very short but still it makes me feel that I cannot scroll down directly after opening the list (which is possible). It's just a very minor UX improvement. I just think it would feel better without the animation.

**Comment by jooooscha** [comment]
As mentioned in #11 animations can be disabled system-wide in the android developer settings. As far as I can tell, that seems to be the best solution to your problem
