### ISSUE TITLE
Make row clickable in full app list

### ISSUE THREAD

**Issue by sebastianha** [OlauncherCF/OlauncherCF#209]
- [X] I have searched existing issues for this feature.

**Is your feature request related to a problem? Please describe.** 

On the main app list you have an option "Extend clickable area on home apps". This is great but it does not apply to the complete app list.

**Describe the solution you'd like** 

I would be nice if this also applies to the complete app list as it makes the apps easier to reach when holding the phone in the other and. The existing config could just apply for all app lists or it is a separate config option.

BTW: Thanks for this great app enhancements and active development!

**Comment by jooooscha** [comment]
Yes, this is a bug introduced in v1.3.0.

Will fix it. Probably in next release.
