### ISSUE TITLE
Text size working wierdly

### ISSUE THREAD

**Issue by ANDREW007CZ** [OlauncherCF/OlauncherCF#212]
1. Go to 'settings (long press)'
2. Click on 'text size'

Text size applies to settings also, making it hard to use with text size set to high 

expected behaviour: text size applies only to homescreen
optionally text size in settings menu is controlled separately

- Olauncher CF Version: 1.3.2
- Install Source: Fdroid
- Device: Sony Xperia 5 III
- Android: stock 12
- EMUI: no EMUI, near stock android
- Other: NA
![Screenshot_20221114-220957](https://user-images.githubusercontent.com/26521196/201767174-736ea289-4d47-4be3-8850-e1ec9a2d38e6.png)
![Screenshot_20221114-221003](https://user-images.githubusercontent.com/26521196/201767189-3277ba58-a7c8-4ecd-a807-16ae8290a51f.png)

**Comment by jooooscha** [comment]
It is intended to have the settings scale too. But I need to align them properly, such that the settings text and the home-screen next is of the same size.

Will fix it in next release

**Comment by ANDREW007CZ** [comment]
In 1.3.3 problem fixed for me. 
Text size option now changes only homescreen text size. Size of the text in settings is not affected. I'm not sure if this is what you wanted according to your reply but for me it works great.

Thank you much!!
