### ISSUE TITLE
Empty space below app list

### ISSUE THREAD

**Issue by Donkey-Doug** [OlauncherCF/OlauncherCF#227]
- [X] I have searched existing issues for this feature.

Add empty space below the app list, such that user do not have to move their thumb in an uncomfortable position to reach the last few apps. 

- Screenshots or other context
![Screenshot_20221214-160352_mLauncher](https://user-images.githubusercontent.com/50382414/207633019-97641644-31f2-4f41-b921-dd724c29838b.png)

youtube, weather and twitter are difficult to reach.

**Comment by Donkey-Doug** [comment]
I would try about 15% of the vertical display room.

**Comment by The-Repo-Club** [comment]
> How large should that space be in your opinion?

i was thinking `android:layout_marginBottom ="50dp"` on the RecyclerView

**Comment by jooooscha** [comment]
I am certainly going to take a look at this, but let me have this question: why is it a problem that the apps are too bar at the bottom? Don't you have to reach there anyway for using the home button and all?

I am just asking to understand your problem a bit better

**Comment by jooooscha** [comment]
> i was thinking android:layout_marginBottom ="50dp" on the RecyclerView

It is currently at `48dp`. I don't think changing it to `50db` would change a whole lot

**Comment by The-Repo-Club** [comment]
> > i was thinking android:layout_marginBottom ="50dp" on the RecyclerView
> 
> It is currently at `48dp`. I don't think changing it to `50dp` would change a lot

ya it has a paddingBottom of 48 but i ment adding a margin of 50 on top of the padding?

**Comment by jooooscha** [comment]
I think this is a very special case and others might like it more the way it is now. But maybe we could add a "hidden" settings area that exposes all margins and paddings? This way everyone could have their paddings exactly how they want to. What do you think?

**Comment by The-Repo-Club** [comment]
ya that could be a good idea too imho i like that idea :)

**Comment by alekksander** [comment]
just a loose thought: not having strong opinion about necessity of bottom margin here, but regarding visual aspect i think it would look good to be symmetrical to the top margin -- the distance between top dash and actual place where apps start to disappear.
