### ISSUE TITLE
Remove _ in app list

### ISSUE THREAD

**Issue by Donkey-Doug** [OlauncherCF/OlauncherCF#228]
- [X] I have searched existing issues for this feature.

#### Motivation behind feature
The design of the other elements of the app is minimal and I think the _ does not fit in.
...

#### Proposed Feature
Remove the _, but keep thr empty space up top to make one-handed use easier.
...

**Comment by jooooscha** [comment]
If I understand you correctly, you mean the `_` that is shown in the app drawer when no text is entered.
Removing would remove the only indicator that there even is a text box. I don't think that would help the user experience

**Comment by The-Repo-Club** [comment]
maybe add this 
```kotlin
if (flag == AppDrawerFlag.LaunchApp) binding.search.queryHint = getString(R.string.show_apps)
```
And
```xml
<string name="show_apps">All apps</string>
```

**Comment by jooooscha** [comment]
Wjat do you mean with move down, when you scroll?

Also, please remember that the pupose of this launcher is to search for apps by typing. Scrolling is not desinged to be your primary selection process

**Comment by The-Repo-Club** [comment]
> Wjat do you mean with move down, when you scroll?
> 
> Also, please remember that the pupose of this launcher is to search for apps by typing. Scrolling is not desinged to be your primary selection process

yeah i know this. he requested the same on my fork and wanted that line to go away if you scroll the applist. i told him thats not possible as its not part of the recyclerview itself

**Comment by jooooscha** [comment]
Ok, you want that thing to be hidden when scrolling.

I don't think that change would improve user experience. Being minima does not mean having as few things on the screen as posssible. It does meen requiering minimal effort to understand the software, which, to some extend, means things like: don't change the headline when moving the list.

**Comment by The-Repo-Club** [comment]
Ya I think having the headline static is nice but OP being a one handed user needs the space :)

**Comment by jooooscha** [comment]
@Donkey-Doug explicitly asked to keep the empty space !?

**Comment by The-Repo-Club** [comment]
> @Donkey-Doug explicitly asked to keep the empty space !?

yes and i also asked him in my fork about having it as text and he said that sounds good too.

**Comment by Donkey-Doug** [comment]
Empty space on the bottom and top is better for one handed use.

**Comment by jooooscha** [comment]
What do you want to have as text?

I am sorry, but I don't really understand your problem and what changes you propose

**Comment by jooooscha** [comment]
Ok, I looked at your thread and I thin I understand your problem.now. However, I am not sure why a text should be more minimal than a simple `_` acting as a prompt. But as you seem to have it impleented in mlauncher, I don't think that thos should be changed in OlauncherCF.

Closing for now. Feel free to open again if you have any more questions
