### ISSUE TITLE
Reorder apps on homescreen

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#231]
- [X] I have searched existing issues for this feature.

#### Motivation behind feature
Make it possible to easily change the order of the apps on the homescreen.

#### Proposed Feature
After press and hold, show an option to drag/reorder.

**Comment by jooooscha** [comment]
The press and hold action is already taken for changing the app. Therefore, this is not an option.

Further, this launcher is designed to be minimal, which includes not to overengineer things like reordering the home screen. Swapping two apps on the home screen is already possible with only two long presses and maybe 2-3 character inputs per app. So, I don't see munch benefit from it. 

Again, this launcher is designed to be minimal and practical. It's aim is not to be the most customizable launcher in the world.

Finally, I am interrested in hearing your oppinion on the goals and non-goals of this project (maybe we should add a list of them to the readme), but I don't think this feature improves the overall experience of the launcher

**Comment by The-Repo-Club** [comment]
Tbh I'm with you it's not that hard to change the apps as it is and adding more complex stuff makes it way more cluttered and less minimal. Recording the apps on the homescreen or even sorting them by most used is kind of a pain to do and I can't really find any launchers that do order by most recently used, the only apps I see that do this are parental controls kind of apps which this is not

**Comment by jooooscha** [comment]
Sorting them by use would also make it impossible to build up muscle memory.
