### ISSUE TITLE
Won't there be more apk files in the github releases?

### ISSUE THREAD

**Issue by ferlanero** [OlauncherCF/OlauncherCF#232]
- [ ] I have searched existing issues for this bug.

#### Bug description

I can't find the apk file since v1.5.0 release 

#### Steps to reproduce

1. Open Github
2. Go to OlauncherCF/OlauncherCF releases
3. v1.5.0
4. There is no apk release

#### Environment information

- Olauncher CF version:
- Device name:
- Android version:
- Other information:

#### Additional context (that might help us to solve your problem)

- signing v1.4.0 with a test signature is enough to make that apk instalable in any Android version.

**Comment by jooooscha** [comment]
This is an ongoing discussion in #196.
Currently, the generated APK is not installable, so I have not included it in the current release. As soon as the APK generation has been fixed, the APK will be included in the release again

**Comment by jooooscha** [comment]
Also related #226

Closing, please use #196 for further discussion
