### ISSUE TITLE
Automatically Open Apps Toggle

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#235]
- [X] I have searched existing issues for this feature.

#### Motivation behind feature

Some people (including me) don't like the apps to auto open

#### Proposed Feature

Automatically Open Apps Toggle (also moved the other toggles from appearance to a toggles category)

#### Additional context

[my PR](https://github.com/HeCodes2Much/mLauncher/pull/42)

**Comment by jooooscha** [comment]
Your PR contains a lot of changes not connected to this feature. So if you open a PR, please clean that up first. Otherwise, I can make this change, too, in the following days. Should be a change of about 10 lines, only.

**Comment by The-Repo-Club** [comment]
Ya ofc I'll only do the changes related to your project :)

**Comment by The-Repo-Club** [comment]
Pushed https://github.com/OlauncherCF/OlauncherCF/pull/236
