### ISSUE TITLE
Allow spaces as name for apps 

### ISSUE THREAD

**Issue by anhsirk0** [OlauncherCF/OlauncherCF#238]
- [X] I have searched existing issues for this feature.

#### Motivation behind feature
I know it sounds ridiculous but It can be used too further hide apps in plain sight.
I previously used Ap15 launcher which has this feature.
...

#### Proposed Feature
Allow few or more spaces as name for app
...

#### Possible alternatives (if applicable)

...

#### Additional context

- Screenshots or other context

**Comment by jooooscha** [comment]
Should be doable. Will take a look at it 👍

**Comment by jooooscha** [comment]
Ok, testing this shows, that renaming apps to a single ` ` makes them completely invisible and having more than one app renamed like this makes it hard to even know where their touch areas are.

Don't you think renaming them to at least a `:` or something similar makes more sense?
I think implementing this could lead to frustration if someone renamed an app to ` ` by mistake.

What do you think?

**Comment by The-Repo-Club** [comment]
i thinking at least having a _ or something is better then a ` ` but that's my opnion

**Comment by anhsirk0** [comment]
I agree that it would be confusing, but that is for the user who wants to name their apps `       `.
About touch area, they are same (full width) for every app (in the app list).
If we add at least `:` or `_` that would defeat the purpose of making an app invisible.

**Comment by The-Repo-Club** [comment]
Tbh hidden apps is there forif you want to hide an app so don't need that really imho

**Comment by jooooscha** [comment]
> About touch area, they are same (full width) for every app (in the app list).

They are, and they also have the same height, but because the ` ` apps are sorted to the top, it's hard to know where one app starts and the other ends. Therefore, it's hard to know where the respective touch areas are.

**Comment by anhsirk0** [comment]
> it's hard to know where the respective touch areas are.  

That is to be expected. 
I think better way would be to just make the app font-color transparent. That way user won't have to bother with renaming.
This would become a completely different feature.

**Comment by jooooscha** [comment]
But that would have the exact same problem?

Maybe, you could elaborate on why using the hiding options does not work for you? Maybe we can find another solution together

**Comment by anhsirk0** [comment]
accessing Hidden apps is kinda a hassle.
1. Long press 2. Click on hidden apps 3. Find the App

maybe there's a better way to get to the hidden apps.

**Comment by jooooscha** [comment]
Would you mind motivating your use case?

Hidden apps are for apps that you need to have installed, only use very rarely. But, you want something to hide your apps, but still use them often? Why hide them, then? If you have any clashes with other apps, you could rename one of them.

**Comment by anhsirk0** [comment]
There isn't much of motivation. Its mainly about freedom of renaming. If any user wants to rename an app, let him rename the app. Olauncher should not care if he uses spaces or unicodes or anything to rename the app. 
If this feature does not align with this projects goals and direction you can close this, I do not intend on wasting your time.
Thank you

**Comment by jooooscha** [comment]
You are not wasting my time; I just want to understand your use case, and find the best possible solution.

I agree that this app is designed for users, who are responsible for what they do. However, it should still behave in expected ways.
And this is my only problem with this. Renaming apps to " " makes it nearly impossible to know where they are in a list, and it's hard to reverse this (Remember, the renamed apps are all sorted to the top). I am happy to allow stupid changes, which makes the app unusable, as said before, the user is responsible, but all changes have to be reversible without reinstalling the app.

Still, if there is a good use case that outweighs this problem, then I have nothing against implementing this.
However, I still don't understand what exactly you want to achieve, what your problem is, and why renaming this to " " helps that.

Do you not agree on the problems I see? I am happy to be corrected.

**Comment by The-Repo-Club** [comment]
We also need the backup and restore feature before adding things that could break the settings so users can do a backup before and restore it if needed.if they do break something?

**Comment by anhsirk0** [comment]
@jooooscha 
I can't think of any usecase  that is worth to consider. I was merely trying to rename an app to `         ` to  make it look transparent. I noticed that I can't do that so I raised this issue. 
While I do agree on your points, I believe that preventing user from doing stupid stuff is not the best solution (at least in this case). Providing a `Reset Defaults` option might be a better way.

**Comment by jooooscha** [comment]
But it will not be transparent; It will be invisible. If the goal is to make the app less distracting, or perhaps less temping to open, your can always reame it to any other visible character, like `­•`, `_`, or `-`.

> I can't think of any usecase that is worth to consider

I take this as: I can close this issue. If someone has new arguments on why we should change this. Please feel free to open a new issue or comment on this one.
