### ISSUE TITLE
Crash on Double Tap gesture

### ISSUE THREAD

**Issue by AntonDzutstsati** [OlauncherCF/OlauncherCF#241]
- [x] I have searched existing issues for this bug.

On Olauncher v1.5.0 when you set "Show App List" on Double Tap gesture - Olauncher crashes.

#### Steps to reproduce

1. Long tap to open settings
2. Set "Show App List" gesture on Double Tap
3. Try it on Home screen.

#### Environment information

- Olauncher CF version: 1.5.0
- Device name: Nokia G10 4/64
- Android version: 11

#### Additional context (that might help us to solve your problem)

- Screenshots or other context

<details> 
  <summary>Screenshot 1</summary>

![Olauncher01.png](https://user-images.githubusercontent.com/74765004/208672253-e8bd532f-398a-4c77-8141-6667638aadb3.png)

</details>
<details> 
  <summary>Screenshot 2</summary>

  ![Screenshot_20221220-165339.png](https://user-images.githubusercontent.com/74765004/208672283-6def1f21-08cc-4fc7-aabc-3ef37a1b7981.png)

</details>

**Comment by jooooscha** [comment]
Thanks for reporting. I will look into this 👍

**Comment by jooooscha** [comment]
should be fixed in 8129dedd1657ac3d938f5a07dd34924bb99743f6
