### ISSUE TITLE
French Settings Menu

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#242]
- [x] I have searched existing issues for this bug.

#### Bug description

Not really a bug because everything is working but french gestures setting is messy

#### Steps to reproduce

1. set language french (or system for some)
2. reopen setting and scroll down to gestures

#### Environment information

N/S does it on any system that uses the french language

#### Additional context (that might help us to solve your problem)

![OlauncherCF in french](https://user-images.githubusercontent.com/49346431/208559435-ad14e60b-87f2-49ff-81c8-fb23145db2b6.jpg)

I think the issue is to do with the text length here are the 2 lines in question that i know of? you dont have them in your own lang file but it was reported on the fork and if i add that to the lang file and build OLCF then it has the same issue 

```
    <string name="show_notifications">Montrer les notifications</string>
    <string name="show_app_list">Afficher la liste des applications</string>
```

**Comment by jooooscha** [comment]
> you dont have them in your own lang file but it was reported on the fork and if i add that to the lang file and build OLCF then it has the same issue

I am sorry, I am not quite sure what you mean by this

**Comment by The-Repo-Club** [comment]
> > you dont have them in your own lang file but it was reported on the fork and if i add that to the lang file and build OLCF then it has the same issue
> 
> I am sorry, I am not quite sure what you mean by this

the 2 lines arn't in your french value-fr file but if i add them then build it the same error happens.... it uses the English system term if not in the string.xml for value-fr

**Comment by The-Repo-Club** [comment]
I think that the text needs a limit of how wide it can be before going to the next line so that it doesn't try to take up all the space for the button and not leave any space for the label. I hope that's understandable :)

**Comment by jooooscha** [comment]
Ok, got it. Will see what I can do

**Comment by The-Repo-Club** [comment]
the new settings page i'm working will not have the same issue as this though so it may be a good idea once its fully tested to give it a look.

**Comment by jooooscha** [comment]
<img src="https://user-images.githubusercontent.com/57965027/209398853-845e169a-2f6d-4478-82e1-6bf42ce7e837.png" width=200px/><img src="https://user-images.githubusercontent.com/57965027/209399226-20c8588b-64cf-425d-9a66-884fdc2912c5.png" width=200px/>


I cannot confirm this bug. On my phone, it looks like this

**Comment by The-Repo-Club** [comment]
Do you also have these?

```xml
    <string name="swipe_left_app">Balayez vers la gauche</string>
    <string name="swipe_right_app">Balayez vers la droite</string>
    <string name="swipe_down_app">Balayez vers le bas</string>
    <string name="swipe_up_app">Balayez vers le haut</string>
```

**Comment by The-Repo-Club** [comment]
ok so it seems like it has fixed itself :)

![image](https://user-images.githubusercontent.com/9284733/209400206-915dc616-dd83-4dae-9ac7-03de070837c3.png)

**Comment by The-Repo-Club** [comment]
could still do with a bit of sizing to make it so buttons are also multi line if too long


![image](https://user-images.githubusercontent.com/9284733/209406574-9d0d2339-cd91-4596-97c2-fd0c4469c41a.png)

**Comment by The-Repo-Club** [comment]
Gonna reopen this a we work out how best to fix it

**Comment by jooooscha** [comment]
I started working on exactly that. Does not need too much change. I will push the branch later, then you could try it on your device

**Comment by jooooscha** [comment]
opened # #250 for it
