### ISSUE TITLE
Olauncher crashes when you confirm app rename with Enter button

### ISSUE THREAD

**Issue by AntonDzutstsati** [OlauncherCF/OlauncherCF#244]
- [x] I have searched existing issues for this bug.

#### Bug description

Tested it with two different keyboards and result is same: when you confirm app rename with "Rename" button there is no problem. But once you press Enter button keyboard launcher crashes.

#### Steps to reproduce

1. On Home Screen swipe up to open App Drawer.
2. Long press any app label.
3. Tap on entry field and press Enter button on your keyboard.

#### Environment information

- Olauncher CF version: 1.5.0
- Device name: Nokia G10
- Android version: 11
- Other information: Keyboards I've used - Simple Keyboard 5.10 by Raimondas Rimkus, Simple Keyboard 5.3.2 by Simple Mobile Tools.

#### Additional context (that might help us to solve your problem)

![Bug_01.png](https://user-images.githubusercontent.com/74765004/209392797-809c3ecc-f801-4067-aed9-c596e6c9ee97.png)
![Bug_02.png](https://user-images.githubusercontent.com/74765004/209392812-7e2a0a98-a519-46b9-9995-09418303590c.png)
![Screenshot_20221223-223044.png](https://user-images.githubusercontent.com/74765004/209392823-ef3fd48d-c5ee-4a97-93b8-884640f777c4.png)

**Comment by jooooscha** [comment]
Thanks for reporting :)
