### ISSUE TITLE
double-tap and click on date synced when "open app" selected

### ISSUE THREAD

**Issue by mikesautkulis** [OlauncherCF/OlauncherCF#251]
- [x] I have searched existing issues for this bug.

#### Bug description
When the "open app" option is selected from either click on date or double-tap gestures changing the app in one will also change the app to launch in the other. 

#### Steps to reproduce

1. Set click on date to open app (select any app).
2. Set double-tap to open app (select any app other than the one previously selected)
3. The app selected for click on date should now be changed to the one selected for double tap. 
4. They will now both open the same app. 

#### Environment information

- Olauncher CF version: 1.5.0
- Device name: Pixel 6a
- Android version: 13
- Other information: build number TQ1A.221205.011

**Comment by jooooscha** [comment]
Thanks for reporting. Copied one constant and forgot to change the name :)
