### ISSUE TITLE
Feature Request Widget Support

### ISSUE THREAD

**Issue by blogmangit** [OlauncherCF/OlauncherCF#257]
- [x] I have searched existing issues for this feature.

#### Motivation behind feature

...Widget support will be great. 

#### Proposed Feature

...Adding Widget support will be a great addition. 

#### Possible alternatives (if applicable)

...No Alternatives.

#### Additional context

<details>
  <summary>Context</summary>

Add your long texts or screenshots here

</details>

**Comment by jooooscha** [comment]
duplicate of #177
