### ISSUE TITLE
Add the abality to make the background go away. or be semi transparent

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#261]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

having an opacity on if you want the wallpaper to show though a solid color background

### Bug description

not a bug so idk what to do here

### Alternatives

also add the ability to change the color of the background at a later time as that's not so easy 

### Additional information

![Peek 2022-12-28 16-42](https://user-images.githubusercontent.com/9284733/209989279-5919cf62-5b31-4572-8e14-9b20d7ca0421.gif)

**Comment by The-Repo-Club** [comment]
if you want this i can do a PR

**Comment by jooooscha** [comment]
Doesn't hurt, I guess :) But we should start to think about how we keep the settings page usable. Recently, we have added a lot of new options.

**Comment by The-Repo-Club** [comment]
> Doesn't hurt, I guess :) But we should start to think about how we keep the settings page usable. Recently, we have added a lot of new options.

ya we can really do with making that page have buttons that go to the category that you click on that way we dont have a mess

example of an idea i have this is one i have on a different launcher i have been working on thats not online yet
![image](https://user-images.githubusercontent.com/9284733/209994928-1fd8105c-8088-4c72-a45e-0acde850f48d.png)

**Comment by The-Repo-Club** [comment]
so i like this :)

![image](https://user-images.githubusercontent.com/9284733/210023304-f9d41387-4746-42a7-ae0d-b8b91d0ac4cd.png)

**Comment by The-Repo-Club** [comment]
i may even switch to sliders where every they need them instead of the button numbers.

**Comment by jooooscha** [comment]
But maybe this is a bit out of scope. You can just edit the image if you want to have it darker. And if you want no image just choose black one. Yes, this can be done by the launcher, but this launcher is minimal so the features should be mininal and focused
