### ISSUE TITLE
Backup only works for english alphabet

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#267]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Bug description

backup does not work with none english a-z A-Z or 0-9 when storing the backup but if you happen to change the string from an english backup you can restore it totaly fine just when you backup again it breaks

Also APP_ALIAS_$num doesnt seem to ever have anything in it for the backup i don't think its ever used.

### Steps to reproduce the bug

1. download a backup to your PC
2. change the string to be non-english
3. put the file back onto the phone
4. restore the setting (this works totaly fine)
5. now re backup the current layout
6. redownload this new backup to the PC (or try to restore and it wont)
7. check the file it has half of the backup missing

### OlauncherCF Version

v1.6.1

### Android Version

13

### Phone

Pixel 7

### Other environment information

Stock OS

### Screenshots/Screen recordings

n/a

### Additional information

n/a

**Comment by The-Repo-Club** [comment]
@jooooscha i do know this is not something that every user is going to do but it still needs to be foolproof cus some people may use it in non english and need to export

**Comment by jooooscha** [comment]
This must be some error with Unicode characters that are more than one byte long. 

Should be fixed in 21932d4064830d9565e8d97a967949e909fa0454

**Comment by The-Repo-Club** [comment]
Cheers

**Comment by The-Repo-Club** [comment]
@jooooscha is APP_ALIAS_$num ment to be empty all the time?

**Comment by The-Repo-Club** [comment]
example below all of the APP_ALIAS_ are empty on backups

<details>
          <summary>CODE</summary>
```
{
	"FIRST_OPEN": false,
	"HIDDEN_APPS_UPDATED": true,
	"APP_ALIAS_9": "",
	"APP_ALIAS_8": "",
	"APP_ALIAS_7": "",
	"APP_ALIAS_6": "",
	"APP_ALIAS_5": "",
	"APP_ALIAS_4": "",
	"APP_PACKAGE_1": "org.mozilla.firefox",
	"APP_PACKAGE_10": "com.android.vending",
	"APP_ACTIVITY_11": "com.android.settings.Settings",
	"APP_ALIAS_3": "",
	"APP_PACKAGE_2": "com.google.android.apps.messaging",
	"APP_PACKAGE_11": "com.android.settings",
	"APP_ALIAS_2": "",
	"APP_ALIAS_1": "",
	"APP_PACKAGE_0": "com.google.android.dialer",
	"APP_ACTIVITY_10": "com.android.vending.AssetBrowserActivity",
	"APP_ALIAS_0": "",
	"APP_PACKAGE_5": "com.google.android.gm",
	"APP_PACKAGE_6": "ch.protonmail.android",
	"APP_PACKAGE_3": "co.uk.getmondo",
	"APP_PACKAGE_4": "arproductions.andrew.expenselog",
	"APP_PACKAGE_9": "com.snapchat.android",
	"APP_PACKAGE_7": "dev.msfjarvis.aps",
	"APP_PACKAGE_8": "com.squareup",
	"APP_NAME_6": "  Proton",
	"APP_USER_2": "UserHandle{0}",
	"APP_USER_11": "UserHandle{0}",
	"APP_ACTIVITY_3": "co.uk.getmondo.splash.SplashActivity",
	"APP_NAME_7": "  Pass",
	"APP_USER_3": "UserHandle{0}",
	"APP_ACTIVITY_2": "com.google.android.apps.messaging.ui.ConversationListActivity",
	"APP_NAME_8": "  Square",
	"APP_USER_4": "UserHandle{0}",
	"APP_ACTIVITY_5": "com.google.android.gm.ConversationListActivityGmail",
	"APP_NAME_9": "例  Snapchat",
	"APP_USER_5": "UserHandle{0}",
	"APP_USER_10": "UserHandle{0}",
	"APP_ACTIVITY_4": "arproductions.andrew.expenselog.MainActivity",
	"APP_ACTIVITY_7": "com.zeapo.pwdstore.LaunchActivity",
	"APP_ACTIVITY_6": "ch.protonmail.android.mailbox.presentation.ui.MailboxActivity",
	"APP_USER_0": "UserHandle{0}",
	"APP_ACTIVITY_9": "com.snapchat.android.LandingPageActivity",
	"APP_USER_1": "UserHandle{0}",
	"APP_ACTIVITY_8": "com.squareup.ui.PaymentActivity",
	"com.android.chrome": "Chrome",
	"APP_ALIAS_10": "",
	"APP_ALIAS_11": "",
	"TIME_ALIGNMENT": "Center",
	"HOME_CLICK_AREA": true,
	"DRAWER_ALIGNMENT": "Right",
	"APP_NAME_0": "  Phone",
	"APP_NAME_1": "  Browser",
	"APP_NAME_2": "  Messages",
	"APP_USER_6": "UserHandle{0}",
	"APP_NAME_3": "  Bank",
	"APP_USER_7": "UserHandle{0}",
	"APP_NAME_4": "  Wages",
	"APP_USER_8": "UserHandle{0}",
	"APP_ACTIVITY_1": "org.mozilla.firefox.App",
	"APP_NAME_5": "  Email",
	"APP_USER_9": "UserHandle{0}",
	"APP_ACTIVITY_0": "com.google.android.dialer.extensions.GoogleDialtactsActivity",
	"FIRST_SETTINGS_OPEN": false,
	"AUTO_OPEN_APP": false,
	"APP_NAME_10": "  Play Store",
	"APP_NAME_11": "  Settings",
	"HOME_ALIGNMENT": "Left",
	"HOME_APPS_NUM": 12
}
```
</details>
