### ISSUE TITLE
Smooth scrolling in Settings

### ISSUE THREAD

**Issue by AntonDzutstsati** [OlauncherCF/OlauncherCF#271]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Bug description

Smooth scrolling doesn't work with disabled system animations. I remember that it didn't work always like that on previous versions of OlauncherCF. Is that a bug or feature?

Tried mLauncher and smooth scrolling works there.

### Steps to reproduce the bug

1. Phone Settings --> Accessibility.
2. Click on "Remove animations".
3. Go to OlauncherCF settings and scroll.

### OlauncherCF Version

v1.6.2

### Android Version

Android 11 (R)

### Phone

Nokia G10

### Screenshots/Screen recordings

Video --> https://drive.google.com/file/d/1tIa1j5PN0wbaDNMtmgdjrV4mYv4z8EcR/view?usp=sharing

**Comment by jooooscha** [comment]
Thanks for reporting. I will look into it

**Comment by jooooscha** [comment]
It seems the jetpack compose function for scrolling does not behave like the old-style Scrollview, at least with the default settings. I have reverted the settings view back to use the Scrollview layout. It should be fixed in v1.6.3
