### ISSUE TITLE
Call specific contact on double tap on screen. (Signal)

### ISSUE THREAD

**Issue by Grkrz** [OlauncherCF/OlauncherCF#273]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

Easier to call the loved ones.

### Feature description

It would be nice if on double tap on a screen the phone wpuld call one of the contacts from Signal or dialer

### Alternatives

It could also be a different movement option or an app tap.

**Comment by jooooscha** [comment]
I think this is out of scope for a minimal launcher.
Unless there is a simple API that could be called?

However, you can just tell OlauncherCF to open signal on double tap, this only adds one or two clicks more to your workflow

**Comment by Grkrz** [comment]
That's completely understandable, thank you for reply.
Unfortunately I don't really know anything about API etc.
Great job with continuing and developing OlauncherCF.
