### ISSUE TITLE
Missing Changelog v1.6.3

### ISSUE THREAD

**Issue by tuch96** [OlauncherCF/OlauncherCF#275]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Bug description

I can't find a changelog for the current version 1.6.3. Can you briefly mention the changes? Thanks!

### Steps to reproduce the bug

Changelog on Github

### OlauncherCF Version

v1.6.3

### Android Version

Android 13

**Comment by The-Repo-Club** [comment]
The dev needs to work out how the action works that creates the change log then it will work until then it's stuck where it is or maybe it will be removed who knows?

**Comment by jooooscha** [comment]
The changelog was added by a PR, I have currently not the time to debug that. Also, this is a very low priority. Closing for now
