### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by 0815cn** [OlauncherCF/OlauncherCF#281]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Bug description

When the system changes from dark mode to normal mode olauncher doesn't change the color of fonts automatically.
The apperance setting of "theme" is set to "system".
My smartphone is set to change the display mode on sunrise/sundown.
What can I do? 

### Steps to reproduce the bug

Just set the android display setting to change display mode scheduled by sunrise/sundown.

### OlauncherCF Version

v1.6.3

### Android Version

Android 11

### Phone

Fairphone 4

**Comment by jooooscha** [comment]
Thanks for reporting.

Does this bug only occur, when using the automatic theme change on sunrise/sunset? When I change the system theme manually, it does correctly change the theme

**Comment by 0815cn** [comment]
It occurs when the system (or I myself manually) change from sunrise to sunset.

But i changed to normal behaviour by deleteing the app settings AND don't use the backup file to restore my settings, but set the same settings manually.

In my former tests to reproduce the "bug", i just delete the app settings or de/reinstalled the app and then restored my settings from the backup.

I don't know whats wrong with the backup file.
But now the app is working as it should.
I will test with the new version (1.6.4).
