### ISSUE TITLE
Feature Request: PIN or password

### ISSUE THREAD

**Issue by timmrogers** [OlauncherCF/OlauncherCF#282]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

This application is almost perfect for my 92 year old mother-in-law.

She finds her phone to be overwhelming, and cannot reliably use standard applications like Phone, Messages, and so on. Olauncher works very well for her.

However, I would like to be able to lock it such that she cannot accidentally make any changes to the configuration. Specifically, she sometimes long-presses on a menu item, and then chooses a different application. This is very confusing and frustrating to her.

### Feature description

If I could set a PIN (different from the unlock code for the phone) which appeared before any configuration option, that would be perfect.

**Comment by jooooscha** [comment]
There is already a setting for locking apps on the home screen. Could you explain why this does not fit your needs?

**Comment by timmrogers** [comment]
Thanks for the reply.

My concern is the my mother in law likes to explore her phone, changes
things, and then is confused and upset. My goal is to make it impossible
for her to do so.

She really only wants and needs a limited set of applications, and no
ability to access anything else on the phone.

Thank you!

**Comment by jooooscha** [comment]
This app is designed for power users; people who don't need Icons to find their apps, and people who know which exact 2 letters to type to get to their app without scrolling through the complete app list. I have the feeling your scenario is quite different from that. Therefore, I am afraid, this app is not the app you are searching.
