### ISSUE TITLE
Search Space Customization, Recents Support & Extending 'Lock Apps'

### ISSUE THREAD

**Issue by ttkdisc** [OlauncherCF/OlauncherCF#283]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

Hello. Thanks for making OLauncher Clutter free!
really liked minimalistic customizable design of this launcher.

i don't like using keyboard for searching apps, have a little list of apps, so all i do is scroll to find desired app. so search space and void at top is clutter for me. and i hope am not alone)

And If possible, are there are any plans to add recents(quickswitch) support.

### Feature description

If there will be an option to disable search space and allow apps to appear from top, it will not only make app more clutterfree for users like me, but will also allow to fit more apps.
![Search_Space](https://user-images.githubusercontent.com/100092868/218273994-8c70738a-64f3-443e-9979-5e6114746be4.jpg)

**Comment by ttkdisc** [comment]
Also. Another request is that enabling 'Lock Apps' Option, disables unwanted long taps on home screen apps. How about extending this functionality to App list too.

**Comment by jooooscha** [comment]
The space is required because in some modes there are buttons shown next to the input.
Further, this launcher is specifically designed to be search-based, Therefore, maybe this is not the right app for you.

What do you mean with quick switch support?

I will think about how to extend the Lock Apps feature

**Comment by ttkdisc** [comment]
I really liked this launcher, thus thought it may become foss alternative to other minimalistic launchers. Nvm. already thankful for this Olauncher fork) 

Root users can change their Recent Screen Provider using [quickswitch](https://github.com/skittles9823/QuickSwitch) . So there is more smooth transitions between Recents screen and Home screen.

**Comment by jooooscha** [comment]
Ok, it seems like there is no documentation for this feature, so I would have to read through the source code of lawnchair. This will require a lot of time and trial-and-error. Therefore, I cannot guarantee that I will have time to do this.
