### ISSUE TITLE
Add battery Indicator to home screen

### ISSUE THREAD

**Issue by zetaomegagon** [OlauncherCF/OlauncherCF#285]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

This has previously brought up in issue [#53](https://github.com/OlauncherCF/OlauncherCF/issues/53). That said, I feel that the choice between showing the status bar (to see the battery indicator), and not showing the battery indicator is a bad compromise.

My reasoning:
- battery status is a heads-up type indicator, where it acts as a quick reminder. Hiding it means extra work to see a reminder...which is kind of antithetical to a reminder
- having to look for the reminder is a distraction
- status bars are often cluttered
- there are some means to de-clutter status bars, but there are some intricacies / caveats:
    - It is not always the case that every Android system icon can be removed from the status bar
    - For every app one needs to modify the app's permissions in order to hide status bar icons

All that said, I really think there is a case for having a small battery indicator on the home screen, along the lines of the one in the original `OLauncher` project.

### Feature description

A minimalist battery indicator will be helpful to users an an easy access, distraction free, reminder. It will avoid the possible clutter if the status bar.

### Alternatives

The alternative would be to enable the status bar or swipe-down to check the battery status periodically.

- the status bar breaks the minimalist continuity of `OLauncher CF` because it's difficult (if not impossible) to have a completely clean status bar save for the battery indicator.
- having to remember to check the battery status with a swipe is having a reminder for a reminder, which isn't optimal
- having to swipe to check is itself a distraction, or opens one to distraction

### Additional information

That's it. Sorry this was kind of long, but I feel pretty strongly about it.

**Comment by tahayparker** [comment]
i second this. just got a S23, the phone looks damn cool but then the status bar has network info, wifi, clock, etc. and it just doesn't fit in with the cleanliness and minimalism of the launcher

**Comment by tahayparker** [comment]
this is someone else's copy of OLauncher right?

**Comment by tahayparker** [comment]
i went ahead and tried it out, the implementation is not that great tbh
i would rather like to have another line saying "Battery 100%" instead of cramming it with the date and time

**Comment by apprehensions** [comment]
Then contribute and fix it.

**Comment by jooooscha** [comment]
Yes, https://github.com/tanujnotes/Olauncher/ is the original, and my version is a hard fork of that.

In my view, my version is as I want it to be (with _maybe_ some minor changes in the future when I see time and need for it). Therefore, if you want a battery indicator, please implement it yourself. My version will feature this in the near future (probably never)
