### ISSUE TITLE
Option to Uninstall App with long press

### ISSUE THREAD

**Issue by Heus-Sueh** [OlauncherCF/OlauncherCF#287]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

having to go to the settings all the time to uninstall an app ends up being a waste of time that could be saved by adding a button to uninstall the app with a long press

### Feature description

maybe a button...
https://jam-icons.com/

### Alternatives

I don't know :thinking: ...

**Comment by Heus-Sueh** [comment]
will this be implemented or not planned?

**Comment by jooooscha** [comment]
Please only check the second button in the issue template only if you have read and understood the corresponding text

**Comment by Heus-Sueh** [comment]
I edited my issue explaining my feature proposal better :+1:

**Comment by jooooscha** [comment]
Searching for "Uninstall" in the issue tab leads to PR #204, maybe you want to take a look at it
