### ISSUE TITLE
Launching uninstalled app shortcut crash

### ISSUE THREAD

**Issue by apprehensions** [OlauncherCF/OlauncherCF#290]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Bug description

Launching an uninstalled app that is set as a shortcut causes Olauncher to crash

### Steps to reproduce the bug

1. Get an app
2. Make it a gesture shortcut
3. Uninstall it
4. Perform the gesture shortcut 
5. Observe

### OlauncherCF Version

v1.6.4

### Android Version

13

### Phone

No

### Other environment information

Nope

**Comment by jooooscha** [comment]
Cannot, confirm on LineageOS (Android 11) with the swipe left gesture. After deinstalling the app and performing the gesture, I get a toast message with "App not found".

In fact, opening an app through a gesture uses the same function as opening an app from the app drawer, so there should be no difference. Could you confirm that?
Further, the actual starting call is in a `try catch` so there should be no runtime exception, but there must be something before that that fails.

Please, provide more information than "No" and "Nope". This would greatly improve my chances of debugging this.

**Comment by apprehensions** [comment]
Yes, for some reason now a toast appears and the crash is gone
