### ISSUE TITLE
Access Alternative/Additional Apps per Row

### ISSUE THREAD

**Issue by brucetheelephant** [OlauncherCF/OlauncherCF#294]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

I'm using multiple apps to do similar things like browsing the internet, reading online news or chatting with different people. For this reason and I simply don't have enough space on the main screen to keep things tidy and show all my frequently used apps at the same time.

### Feature description

I was thinking/wondering/hoping that you could add an option to add multiple apps (or maybe at least two?) to each main screen menu entry and make these accessible by swiping left or right. This way I could add (for example) two similar apps to the first main screen menu entry and then I could swipe left or right on the line to access them.

### Alternatives

I'm not aware that alternatives exist to my request.

### Additional information

At the moment I don't have any additional information to add.

**Comment by R7010A** [comment]
I don´t see any advantage in such a behaviour for most of the users. This is a veeery specific feature.

**Comment by jooooscha** [comment]
I think this goes against the goal of this launcher of being minimal. Also, I see the potential of the gestures conflicting. Therefore, I think this is out of scope for this project. Thanks anyway for you idea :)
