### ISSUE TITLE
Android 14 bug

### ISSUE THREAD

**Issue by Grkrz** [OlauncherCF/OlauncherCF#298]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.
- [X] I know that not filling out all information will greatly reduce the devolopers chances of debugging your issue

### Bug description

Afer updating to android 14 sometimes when using swipe gesture the luncher is crushing. Evyrything dissapring and I have to close the luncher to make it work again. 

### Steps to reproduce the bug

.

### OlauncherCF Version

~Last one available~ (I assume v1.6.5?)

### Android Version

14

### Phone

Pixel 6

**Comment by jooooscha** [comment]
Could you grab a logcat of when the app is crashing?
I need more information to find the bug; I don't own a Android 14 capable device.

**Comment by renegat4** [comment]
I have the same issue.
I captured logcat. But its 20k lines. Its my first time doing this and i dont feel comfortable uploading it. Anything privacy in it? Can i do some grep on it?

**Comment by jooooscha** [comment]
There should be nothing private in it. But you are responsible on what you make public.

That being said, I can only fix this if I have either a logcat, or steps to reproduce.
The current description is not enough to start debugging.

Feel free to reopen with clear information
