### ISSUE TITLE
Publish to the Google Play Store.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [OlauncherCF/OlauncherCF#299]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

I don't want to use F-Droid for this.

### Feature description

> Publish to the Google Play Store.

### Alternatives

F-Droid, as is currently provided.

**Comment by jooooscha** [comment]
Thank you for this considerate issue.

This project is made in my and others free time, and the code is freely available.
That being said, if you don't like f-droid, you are welcome to compile the app yourself.
Alternatively, the current license gives you all permissions to distribute the code, modified or not, in any way.
This includes the Google Play Store.

For further reading on how open-source projects like this generally work, you could read this [mozilla guide](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette), and I am sure there are other good guides on how to write useful first issues online :)

**Comment by RokeJulianLockhart** [comment]
> or further reading on how open-source projects like this generally work, you could read this [mozilla guide](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette), and I am sure there are other good guides on how to write useful first issues online :)

This wasn't?
