### ISSUE TITLE
backup see multiply files when only 1 existing.

### ISSUE THREAD

**Issue by HeCodes2Much** [OlauncherCF/OlauncherCF#306]
### Checklist

- [X] I have searched for existing issues about this bug.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.
- [X] I know that not filling out all information will greatly reduce the devolopers chances of debugging your issue

### Bug description

When saving or loading backups even if there is 1 backup file it will sometimes display 3 4 or 5 depending how many times you have saved the file after you delete it from file system 

### Steps to reproduce the bug

1 save backup
2 try to save again 
3 exit the save and go delete file from files app
4 go to save backup you will see none so save it
5 go to save it again now you will see 2
6 repeat step 3 and 4 
7 now you see 3 saves files even though you only have 1

Every time you deleted the save file then resave it will add a duplicate file.

### OlauncherCF Version

Latest

### Android Version

14

### Phone

Pixel 7

### Additional information

Maybe adding the code below may fix it I haven't tested it but will do later

```kotlin
// Add FLAG_GRANT_READ_URI_PERMISSION to prevent caching
flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
```

**Comment by jooooscha** [comment]
Can't reproduce, please provide more specific instructions.

For example, in step 4: where do you see none (in which app/screen).
Also, in step 3 and 4 you say you store the file:
> you will see none so save it
 Why are you then surprised to have multiple files?

Finally, what do you mean with 
> you see 3 saved files even though you only have 1

Are there three files in the file system?

**Comment by HeCodes2Much** [comment]
if i delete it from Google Files then re save it and Files will say there is only 1 but when i go to save again it will show 2 example below

![image](https://github.com/OlauncherCF/OlauncherCF/assets/9284733/884dc093-2086-4b7e-ae05-f35e6eb5fc82)

![image](https://github.com/OlauncherCF/OlauncherCF/assets/9284733/f065b03f-2aeb-4473-8ac3-5af2d2d6ff05)

**Comment by jooooscha** [comment]
The interface you are describing is part of the android framework. I would not know how my code would influence that.

I strongly assume this is a bug in your OS
